repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks

    rev: v2.0.0

#/bin/bash
    hooks:

    -   id: trailing-whitespace

    -   id: end-of-file-fixer

    -   id: fix-encoding-pragma

    -   id: double-quote-string-fixer

    -   id: requirements-txt-fixer
